---
- include: download_upgrade_package.yml
  when: ghe is not undefined and ghe.upgrade_package_url is defined
- include: run_ghe_update_check.yml
  when: ghe_package_filename is undefined
- include: run_upgrade.yml
