---
- name: set ghe_update_check_cmd with force_upgrade_to_latest
  set_fact:
    ghe_update_check_cmd: "ghe-update-check-OSU -i"
  when: ghe.force_upgrade_to_latest

- name: set ghe_update_check_cmd to default
  set_fact:
    ghe_update_check_cmd: "ghe-update-check-OSU"
  when: ghe_update_check_cmd is undefined

- name: run ghe-update-check
  script: "{{ ghe_update_check_cmd }}"
  register: gheupdatecheck

- name: set ghe_package_filename
  set_fact:
    ghe_package_filename: "{{ gheupdatecheck.stdout_lines | last | basename }}"

- name: enable maintenance mode in GHE
  command: ghe-maintenance -s

- name: wait for active connections to close
  wait_for: host=0.0.0.0 port=443 delay=10 state=drained

- name: set maintenance state in zenoss
  local_action:
    module: zenoss
    zenoss_host: "{{ zenoss.hostname }}"
    user: "{{ zenoss.user }}"
    password: "{{ zenoss.password }}"
    uid: "{{ zenoss_uid }}"
    production_state: maintenance

- name: snapshot VM
  local_action:
    module: vmware
    vsphere:
      host: "{{ vmware.hostname }}"
      user: "{{ vmware.user }}"
      password: "{{ vmware.password }}"
      skip_certcheck: "{{ vmware.skip_certcheck }}"
    guest:
      name: "{{ vm_name }}"
    snapshot:
      action: create
      name: before {{ ghe_package_filename }} upgrade
      include_memory: false

- name: run upgrade
  shell: yes | ghe-upgrade /var/lib/ghe-updates/{{ ghe_package_filename }}
  register: gheupgrade

- name: wait for server restart
  local_action: wait_for host={{ inventory_hostname }} port=443 delay=30

- name: wait for application to come back up
  local_action: command curl -s -k -o /dev/null -w "%{http_code}" https://{{ inventory_hostname }} warn=no
  register: ghe_site
  until: "ghe_site.stdout == '503'"
  retries: 5
  delay: 60

- name: set production state in zenoss
  local_action:
    module: zenoss
    zenoss_host: "{{ zenoss.hostname }}"
    user: "{{ zenoss.user }}"
    password: "{{ zenoss.password }}"
    uid: "{{ zenoss_uid }}"
    production_state: production

- name: disable maintenance mode in GHE
  command: ghe-maintenance -u

- name: wait for sign-in page
  local_action: uri url=https://{{ inventory_hostname }} return_content=true status_code=200 validate_certs=true
  register: ghe_site
  until: "'Enter your ONID username and password to login' in ghe_site.content"
  retries: 5
  delay: 60
